apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cheese.cheddar }}-{{ .Values.cheese.name }}
  labels:
    app: {{ .Values.cheese.cheddar }}-{{ .Values.cheese.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.cheese.port }}
    targetPort: {{ .Values.cheese.targetPort }}
  selector:
    app: {{ .Values.cheese.cheddar }}-{{ .Values.cheese.name }}
  type: {{ .Values.cheese.type }}
