# This shows a secret as a pre-install hook.
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.backendSecrets.name }}
  labels:
    app: {{ template "django-application.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  db-host: {{ .Values.secret.backendSecrets.host }}
  db-port: {{ .Values.secret.backendSecrets.port }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cloudsqlDbCredentials.name }}
  labels:
    app: {{ template "django-application.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  username: {{ .Values.secret.cloudsqlDbCredentials.username }}
  password: {{ .Values.secret.cloudsqlDbCredentials.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.cloudsqlOauthCredentials.name }}
  labels:
    app: {{ template "django-application.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  credentials.json: {{ .Values.secret.cloudsqlOauthCredentials.data }}
